function sum
js-tasks-ru/js-20220418_chislova pull request #1
Opened 2022-04-25 15:36 UTC by Chislova

First task

2022-04-25 15:36 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @dragozin должен запустить тесты.

2022-04-25 16:13 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-25 16:16 UTC, dragozin requested changes

2022-04-25 16:16 UTC, dragozin commented on 01-intro/1-sum/index.js
> +function sum(m, n) {
Экспорт функции нужно оставить, иначе ее нельзя будет использовать в других модулях, в том числе в тестах

2022-04-26 09:37 UTC, jsru commented
Добавляю преподавателя (@dragozin) для код-ревью.

2022-04-26 13:16 UTC, dragozin approved these changes

2022-04-26 13:16 UTC, merged